import {
  ArrowLeftRight,
  Biohazard,
  Boxes,
  ChartNoAxesColumnIncreasing,
  ChartScatter,
  Database,
  Egg,
  Gem,
  Grape,
  House,
  IdCard,
  SquarePen,
} from "lucide-react";

export const searchData = [
  {
    page: "Landing Page",
    url: "/",
    icon: Boxes,
    content: [
      "landing page",
      "home",
      "main",
      "search",
      "about",
      "why",
      "contact",
      "animations",
      "beautiful",
      "tailwind",
      "react",
      "shadcn",
      "next",
      "next.js",
      "supabase",
      "frontend",
      "fullstack",
      "backend",
      "engineer",
      "javascript",
      "typescript",
      "ui/ux",
      "job",
      "career",
      "information",
      "search",
      "about",
      "email",
    ],
  },
  {
    page: "Auth",
    url: "/auth/login",
    icon: IdCard,
    content: [
      "signing up",
      "login",
      "logout",
      "terms of service",
      "privacy policy",
      "animation",
      "name",
      "images",
      "gradient",
      "authentication",
    ],
  },
  {
    page: "Projects",
    url: "/dashboard/projects",
    icon: House,
    content: [
      "my",
      "projects",
      "work experience",
      "nodes",
      "templates",
      "components",
      "flowchart",
      "react flow",
      "list",
      "grid",
      "folders",
      "main",
      "dashboard",
      "career",
      "jobs",
      "search",
      "sidebar",
      "sidenav",
    ],
  },
  {
    page: "Knowledge Bases",
    url: "/dashboard/knowledge-bases",
    icon: Database,
    content: [
      "skills",
      "experience",
      "knowledge",
      "bases",
      "table",
      "grid",
      "list",
      "javascript",
      "serverless",
      "cloud",
      "system",
      "design",
      "ai",
      "ml",
      "hardware",
      "linux",
      "c",
      "c++",
      "c#",
      "rust",
      "wasm",
      "python",
      "java",
      "typescript",
      "react",
      "framer",
      "motion",
      "business",
      "product",
      "development",
      "engineering",
      "filter",
      "search",
      "dashboard",
    ],
  },
  {
    page: "Connections",
    url: "/dashboard/connections",
    icon: ArrowLeftRight,
    content: [
      "cat",
      "pictures",
      "connections",
      "dashboard",
      "jazzymichael",
      "contact",
      "apps",
      "name",
    ],
  },
  {
    page: "Prompt Library",
    url: "/dashboard/prompts",
    icon: SquarePen,
    content: [
      "prompts",
      "library",
      "ai",
      "new",
      "create",
      "description",
      "engineering",
    ],
  },
  {
    page: "Analytics (Dashboard)",
    url: "/dashboard/analytics",
    icon: ChartNoAxesColumnIncreasing,
    content: [
      "dashboard",
      "analytics",
      "project",
      "charts",
      "graphs",
      "data",
      "stackai",
      "ai",
      "phones",
      "metrics",
      "companies",
      "openai",
      "anthropic",
      "gemini",
      "xai",
    ],
  },
  {
    page: "Project Workflow",
    url: "/project/career/workflow",
    icon: Biohazard,
    content: [
      "project",
      "sidebar",
      "sidenav",
      "flowchart",
      "nodes",
      "templates",
      "components",
      "skills",
      "experience",
      "knowledge",
      "bases",
      "table",
      "grid",
      "list",
      "javascript",
      "serverless",
      "cloud",
      "system",
      "design",
      "ai",
      "ml",
      "hardware",
      "linux",
      "c",
      "c++",
      "c#",
      "rust",
      "wasm",
      "python",
      "java",
      "typescript",
      "react",
      "framer",
      "motion",
      "business",
      "product",
      "development",
      "engineering",
      "filter",
      "search",
      "dashboard",
      "workflow",
      "colors",
      "ui",
      "ux",
      "ui/ux",
      "visual",
    ],
  },
  {
    page: "Export",
    url: "/project/career/export",
    icon: Egg,
    content: [
      "project",
      "export",
      "interfaces",
      "form",
      "chatbot",
      "assistant",
    ],
  },
  {
    page: "Analytics (Project)",
    url: "/project/career/analytics",
    icon: ChartScatter,
    content: [
      "project",
      "analytics",
      "charts",
      "graphs",
      "data",
      "stackai",
      "ai",
      "phones",
      "metrics",
      "companies",
      "openai",
      "anthropic",
      "gemini",
      "xai",
    ],
  },
  {
    page: "Manager",
    url: "/project/career/manager",
    icon: Grape,
    content: [
      "project",
      "manager",
      "stackai",
      "ai",
      "companies",
      "technology",
      "internet",
      "live",
      "connect",
      "impact",
      "knowledge",
      "enthusiasm",
      "artificial intelligence",
      "silicon valley",
      "san francisco",
      "amish country",
      "passion",
      "hard",
      "work",
      "culture",
      "creativity",
      "create",
      "ambition",
      "high-impact",
    ],
  },
  {
    page: "Evaluator",
    url: "/project/career/evaluator",
    icon: Gem,
    content: [
      "project",
      "evaluator",
      "data",
      "stackai",
      "ai",
      "companies",
      "jobs",
      "requirements",
      "duties",
      "qualifications",
      "resume",
      "platform",
      "evaluation",
      "skills",
      "experience",
      "knowledge",
      "bases",
      "table",
      "grid",
      "list",
      "javascript",
      "serverless",
      "cloud",
      "system",
      "design",
      "ai",
      "ml",
      "hardware",
      "linux",
      "c",
      "c++",
      "c#",
      "rust",
      "wasm",
      "python",
      "java",
      "typescript",
      "react",
      "framer",
      "motion",
      "business",
      "product",
      "development",
      "engineering",
      "team",
      "collaboration",
      "agent",
      "suggestions",
      "colors",
    ],
  },
];
