export type TableSchema = {
  id: number;
  label: string;
  category: string;
  access: string;
  tokens: string; // change to number
  updated: string;
};

export const tabledata: TableSchema[] = [
  {
    id: 1,
    label: "Typescript/Javascript",
    category: "Frontend, Fullstack",
    access: "Public",
    tokens: "18",
    updated: "Eddie Lake",
  },
  {
    id: 2,
    label: "Serverless & Cloud",
    category: "Backend",
    access: "Public",
    tokens: "29",
    updated: "Eddie Lake",
  },
  {
    id: 3,
    label: "AI & ML",
    category: "General",
    access: "Public",
    tokens: "10",
    updated: "Eddie Lake",
  },
  // {
  //   id: 4,
  //   label: "C# .NET Core",
  //   category: "Narrative",
  //   access: "Public",
  //   tokens: "27",
  //   updated: "Jamik Tashpulatov",
  // },
  {
    id: 5,
    label: "Hardware & Linux",
    category: "General",
    access: "Public",
    tokens: "2",
    updated: "Jamik Tashpulatov",
  },
  {
    id: 6,
    label: "Data Structures & Algorithms",
    category: "General",
    access: "Public",
    tokens: "20",
    updated: "Jamik Tashpulatov",
  },
  {
    id: 7,
    label: "System Design",
    category: "Fullstack",
    access: "Public",
    tokens: "19",
    updated: "Jamik Tashpulatov",
  },
  {
    id: 8,
    label: "C, C++, C#, Rust, WASM",
    category: "Frontend, Backend",
    access: "Public",
    tokens: "25",
    updated: "Assign updated",
  },
  {
    id: 9,
    label: "Python & Java",
    category: "General",
    access: "Public",
    tokens: "7",
    updated: "Assign updated",
  },
  {
    id: 10,
    label: "Product Development & Design",
    category: "Other",
    access: "Public",
    tokens: "30",
    updated: "Assign updated",
  },
  {
    id: 11,
    label: "Business Organization",
    category: "Other",
    access: "Public",
    tokens: "9",
    updated: "Assign updated",
  },
  // {
  //   id: 12,
  //   label: "Mobile - Native & Hybrid",
  //   category: "Narrative",
  //   access: "Public",
  //   tokens: "12",
  //   updated: "Assign updated",
  // },
  {
    id: 15,
    label: "US Nuclear Codes",
    category: "Secrets",
    access: "Private",
    tokens: "3",
    updated: "Assign updated",
  },
  {
    id: 16,
    label: "Agentic Orchestration",
    category: "StackAI",
    access: "Public",
    tokens: "6",
    updated: "Assign updated",
  },
  // {
  //   id: 17,
  //   label: "Scalability and Future Proofing",
  //   category: "Narrative",
  //   access: "Public",
  //   tokens: "4",
  //   updated: "Assign updated",
  // },
  // {
  //   id: 18,
  //   label: "Cost-Benefit Analysis",
  //   category: "Plain language",
  //   access: "Public",
  //   tokens: "14",
  //   updated: "Assign updated",
  // },
  // {
  //   id: 19,
  //   label: "User Training and Onboarding Experience",
  //   category: "Narrative",
  //   access: "Public",
  //   tokens: "17",
  //   updated: "Assign updated",
  // },
  // {
  //   id: 41,
  //   label: "Data Migration Plan",
  //   category: "Technical content",
  //   access: "In Process",
  //   tokens: "19",
  //   updated: "Assign updated",
  // },
  // {
  //   id: 42,
  //   label: "Quality Assurance Protocols",
  //   category: "Technical content",
  //   access: "Public",
  //   tokens: "30",
  //   updated: "Priya Singh",
  // },
  // {
  //   id: 43,
  //   label: "Stakeholder Analysis",
  //   category: "Research",
  //   access: "In Process",
  //   tokens: "11",
  //   updated: "Eddie Lake",
  // },
  // {
  //   id: 44,
  //   label: "Environmental Impact Assessment",
  //   category: "Research",
  //   access: "Public",
  //   tokens: "24",
  //   updated: "Assign updated",
  // },
];
