export type TableSchema = {
  id: number;
  label: string;
  category: string;
  access: string;
  tokens: string; // change to number
  updated: string;
};

export const tabledata: TableSchema[] = [
  {
    id: 1,
    label: "Cover page",
    category: "Cover page",
    access: "In Process",
    tokens: "18",
    updated: "Eddie Lake",
  },
  {
    id: 2,
    label: "Table of contents",
    category: "Table of contents",
    access: "Public",
    tokens: "29",
    updated: "Eddie Lake",
  },
  {
    id: 3,
    label: "Executive summary",
    category: "Narrative",
    access: "Public",
    tokens: "10",
    updated: "Eddie Lake",
  },
  {
    id: 4,
    label: "Technical approach",
    category: "Narrative",
    access: "Public",
    tokens: "27",
    updated: "Jamik Tashpulatov",
  },
  {
    id: 5,
    label: "Design",
    category: "Narrative",
    access: "In Process",
    tokens: "2",
    updated: "Jamik Tashpulatov",
  },
  {
    id: 6,
    label: "Capabilities",
    category: "Narrative",
    access: "In Process",
    tokens: "20",
    updated: "Jamik Tashpulatov",
  },
  {
    id: 7,
    label: "Integration with existing systems",
    category: "Narrative",
    access: "In Process",
    tokens: "19",
    updated: "Jamik Tashpulatov",
  },
  {
    id: 8,
    label: "Innovation and Advantages",
    category: "Narrative",
    access: "Public",
    tokens: "25",
    updated: "Assign updated",
  },
  {
    id: 9,
    label: "Overview of EMR's Innovative Solutions",
    category: "Technical content",
    access: "Public",
    tokens: "7",
    updated: "Assign updated",
  },
  {
    id: 10,
    label: "Advanced Algorithms and Machine Learning",
    category: "Narrative",
    access: "Public",
    tokens: "30",
    updated: "Assign updated",
  },
  {
    id: 11,
    label: "Adaptive Communication Protocols",
    category: "Narrative",
    access: "Public",
    tokens: "9",
    updated: "Assign updated",
  },
  {
    id: 12,
    label: "Advantages Over Current Technologies",
    category: "Narrative",
    access: "Public",
    tokens: "12",
    updated: "Assign updated",
  },
  {
    id: 13,
    label: "Past Performance",
    category: "Narrative",
    access: "Public",
    tokens: "22",
    updated: "Assign updated",
  },
  {
    id: 14,
    label: "Customer Feedback and Satisfaction Levels",
    category: "Narrative",
    access: "Public",
    tokens: "15",
    updated: "Assign updated",
  },
  {
    id: 15,
    label: "Implementation Challenges and Solutions",
    category: "Narrative",
    access: "Public",
    tokens: "3",
    updated: "Assign updated",
  },
  {
    id: 16,
    label: "Security Measures and Data Protection Policies",
    category: "Narrative",
    access: "In Process",
    tokens: "6",
    updated: "Assign updated",
  },
  {
    id: 17,
    label: "Scalability and Future Proofing",
    category: "Narrative",
    access: "Public",
    tokens: "4",
    updated: "Assign updated",
  },
  {
    id: 18,
    label: "Cost-Benefit Analysis",
    category: "Plain language",
    access: "Public",
    tokens: "14",
    updated: "Assign updated",
  },
  {
    id: 19,
    label: "User Training and Onboarding Experience",
    category: "Narrative",
    access: "Public",
    tokens: "17",
    updated: "Assign updated",
  },
  {
    id: 41,
    label: "Data Migration Plan",
    category: "Technical content",
    access: "In Process",
    tokens: "19",
    updated: "Assign updated",
  },
  {
    id: 42,
    label: "Quality Assurance Protocols",
    category: "Technical content",
    access: "Public",
    tokens: "30",
    updated: "Priya Singh",
  },
  {
    id: 43,
    label: "Stakeholder Analysis",
    category: "Research",
    access: "In Process",
    tokens: "11",
    updated: "Eddie Lake",
  },
  {
    id: 44,
    label: "Environmental Impact Assessment",
    category: "Research",
    access: "Public",
    tokens: "24",
    updated: "Assign updated",
  },
];
